packages:
  - 'apps/api/*'
  - 'apps/web/aaf/*'
  - 'apps/web/pages/dashboard'
  - 'apps/web/pages/site'
  - 'packages/*'
allowBuilds:
  better-sqlite3: false
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAge: 0
registrySupportsTimeField: true
