packages:
  - 'apps/api/*'
  - 'apps/web/aaf/*'
  - 'apps/web/dashboard'
  - 'apps/web/site'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
registrySupportsTimeField: true
