-- Dev seed — generated by drizzle/seed/dev.ts
-- Generated: 2026-06-30T00:42:00.860Z

-- ─── Agents ───────────────────────────────────────────────────────────────

INSERT OR REPLACE INTO agents (id, name, slug, description, system_prompt, tools_enabled, model_provider, model_id, channel, is_active, created_at, updated_at) VALUES (
  'agent-taji-001', 'Taji', 'taji', 'Career document agent',
  'You are Taji, a professional career document assistant. Help users create CVs, cover letters, and resignation letters. Be warm, professional, and encouraging.',
  '["listSKUs","collectField","initiatePayment","generateDocument"]', 'openrouter', 'openai/gpt-4o-mini', 'whatsapp', 1, '2026-06-30T00:42:00.860Z', '2026-06-30T00:42:00.860Z'
);

INSERT OR REPLACE INTO agents (id, name, slug, description, system_prompt, tools_enabled, model_provider, model_id, channel, is_active, created_at, updated_at) VALUES (
  'agent-elim-001', 'Elim', 'elim', 'CBC education agent',
  'You are Elim, a friendly CBC education assistant. Help Kenyan students with exam prep, concept explanations, and practice questions.',
  '["askQuestion","explainConcept","givePractice"]', 'openrouter', 'openai/gpt-4o-mini', 'whatsapp', 1, '2026-06-30T00:42:00.860Z', '2026-06-30T00:42:00.860Z'
);


-- ─── SKUs ───────────────────────────────────────────────────────────────────

INSERT OR REPLACE INTO skus (id, name, slug, description, agent_slug, template_type, file_key, preview_key, markdown_preview, price, currency, field_schema, conversation_steps, is_active, requires_review, version, created_at, updated_at) VALUES (
  'sku-cv-001', 'Professional CV', 'professional-cv', 'A clean professional CV for any industry in Kenya.',
  'taji', 'docx', 'templates/cv-professional-v1.docx',
  NULL, 'Professional CV template',
  250, 'KES',
  '[{"key":"full_name","label":"Full Name","type":"text","required":true,"hint":"Your full legal name"},{"key":"phone","label":"Phone Number","type":"text","required":true,"hint":"e.g. 0712345678"},{"key":"email","label":"Email Address","type":"text","required":true,"hint":"e.g. jane@gmail.com"},{"key":"location","label":"Location / City","type":"text","required":true,"hint":"e.g. Nairobi"},{"key":"job_title","label":"Target Job Title","type":"text","required":true,"hint":"Position you are applying for"},{"key":"summary","label":"Professional Summary","type":"text","required":true,"hint":"2-3 sentences about your background"},{"key":"experience","label":"Work Experience","type":"text","required":true,"hint":"e.g. Cashier at Naivas (2020-2022)"},{"key":"education","label":"Education","type":"text","required":true,"hint":"e.g. KCSE 2019, Starehe Boys Centre"},{"key":"skills","label":"Key Skills","type":"text","required":true,"hint":"e.g. Customer service, MS Office"},{"key":"languages","label":"Languages","type":"text","required":true,"hint":"e.g. English, Swahili"}]',
  '[{"id":"step-1","prompt":"1/10 — Full Name\nYour full legal name","fieldKey":"full_name"},{"id":"step-2","prompt":"2/10 — Phone Number\ne.g. 0712345678","fieldKey":"phone"},{"id":"step-3","prompt":"3/10 — Email Address\ne.g. jane@gmail.com","fieldKey":"email"},{"id":"step-4","prompt":"4/10 — Location / City\ne.g. Nairobi","fieldKey":"location"},{"id":"step-5","prompt":"5/10 — Target Job Title\nPosition you are applying for","fieldKey":"job_title"},{"id":"step-6","prompt":"6/10 — Professional Summary\n2-3 sentences about your background","fieldKey":"summary"},{"id":"step-7","prompt":"7/10 — Work Experience\ne.g. Cashier at Naivas (2020-2022)","fieldKey":"experience"},{"id":"step-8","prompt":"8/10 — Education\ne.g. KCSE 2019, Starehe Boys Centre","fieldKey":"education"},{"id":"step-9","prompt":"9/10 — Key Skills\ne.g. Customer service, MS Office","fieldKey":"skills"},{"id":"step-10","prompt":"10/10 — Languages\ne.g. English, Swahili","fieldKey":"languages"}]',
  1, 0, 1, '2026-06-30T00:42:00.860Z', '2026-06-30T00:42:00.860Z'
);

INSERT OR REPLACE INTO skus (id, name, slug, description, agent_slug, template_type, file_key, preview_key, markdown_preview, price, currency, field_schema, conversation_steps, is_active, requires_review, version, created_at, updated_at) VALUES (
  'sku-cover-001', 'Application / Cover Letter', 'cover-letter', 'A persuasive cover letter tailored to the job.',
  'taji', 'docx', 'templates/cover-letter-v1.docx',
  NULL, 'Application / Cover Letter template',
  150, 'KES',
  '[{"key":"full_name","label":"Full Name","type":"text","required":true,"hint":""},{"key":"phone","label":"Phone Number","type":"text","required":true,"hint":""},{"key":"email","label":"Email Address","type":"text","required":true,"hint":""},{"key":"job_title","label":"Job You Are Applying For","type":"text","required":true,"hint":""},{"key":"company_name","label":"Company Name","type":"text","required":true,"hint":""},{"key":"hiring_manager","label":"Hiring Manager Name","type":"text","required":true,"hint":"Leave blank if unknown"},{"key":"why_interested","label":"Why do you want this job?","type":"text","required":true,"hint":"1-2 sentences"},{"key":"key_achievement","label":"Your Biggest Achievement","type":"text","required":true,"hint":"A result you are proud of"},{"key":"availability","label":"When can you start?","type":"text","required":true,"hint":"e.g. Immediately"}]',
  '[{"id":"step-1","prompt":"1/9 — Full Name","fieldKey":"full_name"},{"id":"step-2","prompt":"2/9 — Phone Number","fieldKey":"phone"},{"id":"step-3","prompt":"3/9 — Email Address","fieldKey":"email"},{"id":"step-4","prompt":"4/9 — Job You Are Applying For","fieldKey":"job_title"},{"id":"step-5","prompt":"5/9 — Company Name","fieldKey":"company_name"},{"id":"step-6","prompt":"6/9 — Hiring Manager Name\nLeave blank if unknown","fieldKey":"hiring_manager"},{"id":"step-7","prompt":"7/9 — Why do you want this job?\n1-2 sentences","fieldKey":"why_interested"},{"id":"step-8","prompt":"8/9 — Your Biggest Achievement\nA result you are proud of","fieldKey":"key_achievement"},{"id":"step-9","prompt":"9/9 — When can you start?\ne.g. Immediately","fieldKey":"availability"}]',
  1, 0, 1, '2026-06-30T00:42:00.860Z', '2026-06-30T00:42:00.860Z'
);

INSERT OR REPLACE INTO skus (id, name, slug, description, agent_slug, template_type, file_key, preview_key, markdown_preview, price, currency, field_schema, conversation_steps, is_active, requires_review, version, created_at, updated_at) VALUES (
  'sku-resign-001', 'Resignation Letter', 'resignation-letter', 'Professional resignation letter with notice period.',
  'taji', 'docx', 'templates/resignation-letter-v1.docx',
  NULL, 'Resignation Letter template',
  100, 'KES',
  '[{"key":"full_name","label":"Your Full Name","type":"text","required":true,"hint":""},{"key":"current_job_title","label":"Your Current Job Title","type":"text","required":true,"hint":""},{"key":"company_name","label":"Company Name","type":"text","required":true,"hint":""},{"key":"manager_name","label":"Manager''s Name","type":"text","required":true,"hint":""},{"key":"last_working_day","label":"Last Working Day","type":"text","required":true,"hint":"e.g. 15 July 2025"},{"key":"reason","label":"Reason for Leaving","type":"text","required":true,"hint":"Optional — brief and professional"},{"key":"notice_period","label":"Notice Period","type":"text","required":true,"hint":"e.g. 1 month"}]',
  '[{"id":"step-1","prompt":"1/7 — Your Full Name","fieldKey":"full_name"},{"id":"step-2","prompt":"2/7 — Your Current Job Title","fieldKey":"current_job_title"},{"id":"step-3","prompt":"3/7 — Company Name","fieldKey":"company_name"},{"id":"step-4","prompt":"4/7 — Manager''s Name","fieldKey":"manager_name"},{"id":"step-5","prompt":"5/7 — Last Working Day\ne.g. 15 July 2025","fieldKey":"last_working_day"},{"id":"step-6","prompt":"6/7 — Reason for Leaving\nOptional — brief and professional","fieldKey":"reason"},{"id":"step-7","prompt":"7/7 — Notice Period\ne.g. 1 month","fieldKey":"notice_period"}]',
  1, 0, 1, '2026-06-30T00:42:00.860Z', '2026-06-30T00:42:00.860Z'
);

