-- Dev seed — generated by drizzle/seed/dev.ts
-- Generated at: 2026-06-30T10:58:31.744Z

-- ─── Agents ──────────────────────────────────────────────────────────────

INSERT OR REPLACE INTO agents (id, name, slug, description, system_prompt, tools_enabled, model_provider, model_id, channel, channel_config, is_active, created_at, updated_at) VALUES (
  'agent-taji-001', 'Taji', 'taji', 'Career document agent — CVs, cover letters, resignation letters',
  'You are Taji, a professional career document assistant.
You help users create CVs, application letters, and resignation letters.
Be warm, professional, and encouraging.
Always collect all required fields before generating a document.',
  '["listSKUs","collectField","initiatePayment","generateDocument"]', 'openrouter', 'meta-llama/llama-3.1-8b-instruct:free',
  'whatsapp', '{"whatsappPhoneNumberId":"1038436689362682"}', 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO agents (id, name, slug, description, system_prompt, tools_enabled, model_provider, model_id, channel, channel_config, is_active, created_at, updated_at) VALUES (
  'agent-elim-001', 'Elim', 'elim', 'CBC education agent — exam prep, tutoring for Kenyan students',
  'You are Elim, a friendly CBC education assistant for Kenyan students.
You help with exam preparation, concept explanations, and practice questions.
Always encourage students and explain things clearly in simple language.',
  '["askQuestion","explainConcept","givePractice"]', 'openrouter', 'meta-llama/llama-3.1-8b-instruct:free',
  'whatsapp', '{"whatsappPhoneNumberId":"729899760214979"}', 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO agents (id, name, slug, description, system_prompt, tools_enabled, model_provider, model_id, channel, channel_config, is_active, created_at, updated_at) VALUES (
  'agent-test-001', 'Test', 'test', 'General-purpose test agent for WhatsApp flow testing',
  'You are a test agent for WhatsApp flow testing.
Respond concisely and confirm that messages are being routed correctly.
Identify yourself as the test agent when asked.',
  '["listSKUs","collectField"]', 'openrouter', 'meta-llama/llama-3.1-8b-instruct:free',
  'whatsapp', '{"whatsappPhoneNumberId":"122108114672001278"}', 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);


-- ─── SKUs ────────────────────────────────────────────────────────────────

INSERT OR REPLACE INTO skus (id, name, slug, description, template_type, file_key, preview_key, markdown_preview, price, currency, field_schema, conversation_steps, is_active, requires_review, version, created_at, updated_at) VALUES (
  'sku-cv-professional-001', 'Professional CV', 'professional-cv', 'A clean, professional CV template suitable for all industries in Kenya.',
  'docx', 'templates/cv-professional-v1.docx',
  NULL, '## Professional CV
Name, contact, summary, experience, education, skills.',
  1, 'KES',
  '[{"key":"full_name","label":"Full Name","type":"text","required":true,"hint":"Your full legal name as it appears on your ID"},{"key":"phone","label":"Phone Number","type":"text","required":true,"hint":"e.g. 0712345678"},{"key":"email","label":"Email Address","type":"text","required":true,"hint":"e.g. jane@gmail.com"},{"key":"location","label":"Location / City","type":"text","required":true,"hint":"e.g. Nairobi, Karen"},{"key":"job_title","label":"Target Job Title","type":"text","required":true,"hint":"The position you are applying for"},{"key":"summary","label":"Professional Summary","type":"text","required":true,"hint":"2-3 sentences about your background and goals"},{"key":"experience","label":"Work Experience","type":"text","required":true,"hint":"List jobs: title at company (years). e.g. Cashier at Naivas (2020-2022)"},{"key":"education","label":"Education","type":"text","required":true,"hint":"e.g. KCSE 2019, Starehe Boys Centre"},{"key":"skills","label":"Key Skills","type":"text","required":true,"hint":"e.g. Customer service, MS Office, teamwork"},{"key":"languages","label":"Languages","type":"text","required":false,"hint":"e.g. English, Swahili, Kikuyu"}]',
  '[{"id":"step-1","prompt":"1/10 — *Full Name*\nYour full legal name as it appears on your ID","fieldKey":"full_name","validation":"required"},{"id":"step-2","prompt":"2/10 — *Phone Number*\ne.g. 0712345678","fieldKey":"phone","validation":"phone"},{"id":"step-3","prompt":"3/10 — *Email Address*\ne.g. jane@gmail.com","fieldKey":"email","validation":"email"},{"id":"step-4","prompt":"4/10 — *Location / City*\ne.g. Nairobi, Karen","fieldKey":"location","validation":"required"},{"id":"step-5","prompt":"5/10 — *Target Job Title*\nThe position you are applying for","fieldKey":"job_title","validation":"required"},{"id":"step-6","prompt":"6/10 — *Professional Summary*\n2-3 sentences about your background and goals","fieldKey":"summary","validation":"required"},{"id":"step-7","prompt":"7/10 — *Work Experience*\nList jobs: title at company (years). e.g. Cashier at Naivas (2020-2022)","fieldKey":"experience","validation":"required"},{"id":"step-8","prompt":"8/10 — *Education*\ne.g. KCSE 2019, Starehe Boys Centre","fieldKey":"education","validation":"required"},{"id":"step-9","prompt":"9/10 — *Key Skills*\ne.g. Customer service, MS Office, teamwork","fieldKey":"skills","validation":"required"},{"id":"step-10","prompt":"10/10 — *Languages*\ne.g. English, Swahili, Kikuyu","fieldKey":"languages","validation":"required"}]',
  1, 0, 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO skus (id, name, slug, description, template_type, file_key, preview_key, markdown_preview, price, currency, field_schema, conversation_steps, is_active, requires_review, version, created_at, updated_at) VALUES (
  'sku-cover-letter-001', 'Application / Cover Letter', 'cover-letter', 'A persuasive cover letter tailored to the specific job and company.',
  'docx', 'templates/cover-letter-v1.docx',
  NULL, '## Cover Letter
Introduction, body, closing, signature.',
  2, 'KES',
  '[{"key":"full_name","label":"Full Name","type":"text","required":true},{"key":"phone","label":"Phone Number","type":"text","required":true},{"key":"email","label":"Email Address","type":"text","required":true},{"key":"job_title","label":"Job You Are Applying For","type":"text","required":true},{"key":"company_name","label":"Company Name","type":"text","required":true},{"key":"hiring_manager","label":"Hiring Manager Name","type":"text","required":false,"hint":"Leave blank if unknown"},{"key":"why_interested","label":"Why do you want this job?","type":"text","required":true,"hint":"1-2 sentences"},{"key":"key_achievement","label":"Your Biggest Achievement","type":"text","required":true,"hint":"A result you are proud of"},{"key":"availability","label":"When can you start?","type":"text","required":true,"hint":"e.g. Immediately, 2 weeks notice"}]',
  '[{"id":"step-1","prompt":"1/9 — *Full Name*","fieldKey":"full_name","validation":"required"},{"id":"step-2","prompt":"2/9 — *Phone Number*","fieldKey":"phone","validation":"required"},{"id":"step-3","prompt":"3/9 — *Email Address*","fieldKey":"email","validation":"email"},{"id":"step-4","prompt":"4/9 — *Job You Are Applying For*","fieldKey":"job_title","validation":"required"},{"id":"step-5","prompt":"5/9 — *Company Name*","fieldKey":"company_name","validation":"required"},{"id":"step-6","prompt":"6/9 — *Hiring Manager Name*\nLeave blank if unknown","fieldKey":"hiring_manager","validation":"required"},{"id":"step-7","prompt":"7/9 — *Why do you want this job?*\n1-2 sentences","fieldKey":"why_interested","validation":"required"},{"id":"step-8","prompt":"8/9 — *Your Biggest Achievement*\nA result you are proud of","fieldKey":"key_achievement","validation":"required"},{"id":"step-9","prompt":"9/9 — *When can you start?*\ne.g. Immediately, 2 weeks notice","fieldKey":"availability","validation":"required"}]',
  1, 0, 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO skus (id, name, slug, description, template_type, file_key, preview_key, markdown_preview, price, currency, field_schema, conversation_steps, is_active, requires_review, version, created_at, updated_at) VALUES (
  'sku-resignation-001', 'Resignation Letter', 'resignation-letter', 'A professional resignation letter with proper notice period.',
  'docx', 'templates/resignation-letter-v1.docx',
  NULL, '## Resignation Letter
Formal notice of resignation with last working day.',
  3, 'KES',
  '[{"key":"full_name","label":"Your Full Name","type":"text","required":true},{"key":"current_job_title","label":"Your Current Job Title","type":"text","required":true},{"key":"company_name","label":"Company Name","type":"text","required":true},{"key":"manager_name","label":"Manager''s Name","type":"text","required":true},{"key":"last_working_day","label":"Last Working Day","type":"date","required":true,"hint":"e.g. 15 July 2025"},{"key":"reason","label":"Reason for Leaving","type":"text","required":false,"hint":"Optional — brief and professional"},{"key":"notice_period","label":"Notice Period","type":"text","required":true,"hint":"e.g. 1 month, 2 weeks"}]',
  '[{"id":"step-1","prompt":"1/7 — *Your Full Name*","fieldKey":"full_name","validation":"required"},{"id":"step-2","prompt":"2/7 — *Your Current Job Title*","fieldKey":"current_job_title","validation":"required"},{"id":"step-3","prompt":"3/7 — *Company Name*","fieldKey":"company_name","validation":"required"},{"id":"step-4","prompt":"4/7 — *Manager''s Name*","fieldKey":"manager_name","validation":"required"},{"id":"step-5","prompt":"5/7 — *Last Working Day*\ne.g. 15 July 2025","fieldKey":"last_working_day","validation":"required"},{"id":"step-6","prompt":"6/7 — *Reason for Leaving*\nOptional — brief and professional","fieldKey":"reason","validation":"required"},{"id":"step-7","prompt":"7/7 — *Notice Period*\ne.g. 1 month, 2 weeks","fieldKey":"notice_period","validation":"required"}]',
  1, 0, 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO skus (id, name, slug, description, template_type, file_key, preview_key, markdown_preview, price, currency, field_schema, conversation_steps, is_active, requires_review, version, created_at, updated_at) VALUES (
  'sku-basic-cv-free-001', 'Basic CV (Free)', 'basic-cv-free', 'A simple CV with just your name, phone and target job — free, no payment needed.',
  'docx', 'templates/basic-cv-free-v1.docx',
  NULL, '## Basic CV
Name, phone, target job.',
  0, 'KES',
  '[{"key":"full_name","label":"Full Name","type":"text","required":true,"hint":"Your full name"},{"key":"phone","label":"Phone Number","type":"text","required":true,"hint":"e.g. 0712345678"},{"key":"job_title","label":"Target Job","type":"text","required":false,"hint":"e.g. Software Developer"}]',
  '[{"id":"step-1","prompt":"1/3 — *Full Name*\nYour full name","fieldKey":"full_name","validation":"required"},{"id":"step-2","prompt":"2/3 — *Phone Number*\ne.g. 0712345678","fieldKey":"phone","validation":"phone"},{"id":"step-3","prompt":"3/3 — *Target Job*\ne.g. Software Developer","fieldKey":"job_title"}]',
  1, 0, 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);


-- ─── SKU-Agent Access ────────────────────────────────────────────────────────

INSERT OR REPLACE INTO sku_agent_access (id, sku_id, agent_slug, enabled, created_at, updated_at) VALUES (
  'access-saa-cv-taji-001', 'sku-cv-professional-001', 'taji', 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO sku_agent_access (id, sku_id, agent_slug, enabled, created_at, updated_at) VALUES (
  'access-saa-cv-elim-001', 'sku-cv-professional-001', 'elim', 0, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO sku_agent_access (id, sku_id, agent_slug, enabled, created_at, updated_at) VALUES (
  'access-saa-cover-taji-001', 'sku-cover-letter-001', 'taji', 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO sku_agent_access (id, sku_id, agent_slug, enabled, created_at, updated_at) VALUES (
  'access-saa-cover-elim-001', 'sku-cover-letter-001', 'elim', 0, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO sku_agent_access (id, sku_id, agent_slug, enabled, created_at, updated_at) VALUES (
  'access-saa-resign-taji-001', 'sku-resignation-001', 'taji', 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO sku_agent_access (id, sku_id, agent_slug, enabled, created_at, updated_at) VALUES (
  'access-saa-resign-elim-001', 'sku-resignation-001', 'elim', 0, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO sku_agent_access (id, sku_id, agent_slug, enabled, created_at, updated_at) VALUES (
  'access-saa-basic-taji-001', 'sku-basic-cv-free-001', 'taji', 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

INSERT OR REPLACE INTO sku_agent_access (id, sku_id, agent_slug, enabled, created_at, updated_at) VALUES (
  'access-saa-basic-elim-001', 'sku-basic-cv-free-001', 'elim', 1, '2026-06-30T10:58:31.744Z', '2026-06-30T10:58:31.744Z'
);

